### ISSUE TITLE
Wildcard in file path

### ISSUE THREAD

**Issue by jimafisk** [parnic/go-assetprecompiler#3]
Is it possible to reference all files in a given folder using a wildcard, something like an asterisk (*)?

For example if I had many "component" css files in a directory, could I just point to the directory instead of each file individually? Given a tree structure like this:

```
|--assets/
|----css/
|----main.css
|----components/
|------slider.css
|------grid.css
|------button.css
|------tabs.css
|----public/
|------css/
```

Concatenate `slider.css`, `grid.css`, `button.css`, and `tabs.css` with this code:
```go
precompiler.Compile(precompiler.Config{
  Files: []string{
    "assets/css/main.css",
    "assets/css/components/*.css",
  },
  Minify:    true,
  OutputDir: "assets/public/",
})
```

**Comment by parnic** [comment]
This would certainly be possible with some code modifications, which I'd be happy to accept a PR for, but at the moment it's not possible. My intent here was to allow precompiling files in specific orders so that files which depended on other files, such as bootstrap/jquery, could be precompiled in an explicit order whereas globbing them all together could cause errors. If a PR was going to extend how files can be loaded, I'd probably want to move toward some sort of existing abstraction like http.FileSystem.
